services:
  database:
    container_name: database
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: tandera
    volumes:
      - database-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
volumes:
  database-data: