services:
  database:
    image: "postgres"
    volumes:
      - database-data:/bar/lib/posrgresql/ata
  backend:
    container_name: backend
    build: 
      context: ./backend
    dockerfile: Dockerfile
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    dockerfile: Dockerfile
volumes:
  database-data: 
    
  